name: Update README Age

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update age in README
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const dob = '2005-01-18';
            const age = Math.floor((new Date() - new Date(dob)) / 31557600000);
            const readmePath = 'README.md';
            let readmeContent = fs.readFileSync(readmePath, 'utf8');
            readmeContent = readmeContent.replace(
              /https://img\.shields\.io\/badge\/Age-\d+-blue\?style=for-the-badge/,
              `https://img.shields.io/badge/Age-${age}-blue?style=for-the-badge`
            );
            fs.writeFileSync(readmePath, readmeContent);
            console.log(`Updated age to ${age}`);

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: 🎉 Update age in README" && git push)
